# Generated by Django 5.0.7 on 2024-07-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
