# Generated by Django 5.0.7 on 2024-07-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_favorite'),
        ('todo', '0003_alter_like_unique_together_alter_like_task'),
    ]

    operations = [
    ]
