# Generated by Django 5.0.7 on 2024-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_merge_20240724_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
