# Generated by Django 5.0.7 on 2024-07-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_likes_count_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='genre',
            field=models.CharField(choices=[('report', 'Report'), ('program', 'Program'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
