# Generated by Django 5.0.7 on 2024-07-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_photo'),
        ('todo', '0006_task_genre'),
    ]

    operations = [
    ]
